---
apiVersion: v1
kind: Service
metadata:
  name: fabric-ca-k8s
spec:
  selector:
    app: fabric-ca
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054
    name: https    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-ca-k8s
  labels: 
    app: fabric-ca-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-ca-k8s
  template:
    metadata:
      labels:
        app: fabric-ca-k8s
    spec:
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: mypvc

      containers:
      - name: fabric-ca-k8s
        image: hyperledger/fabric-ca:1.4.4
        command: ["sh", "-c", "sleep 1 && fabric-ca-server start -d --cfg.identities.allowremove --port 7054"]
        env:
        - name: FABRIC_CA_SERVER_HOME
          value: /etc/hyperledger/fabric-ca/k8s
        - name: FABRIC_CA_SERVER_CSR_CN
          value: "fabric-ca-k8s"
        - name: FABRIC_CA_SERVER_CSR_HOSTS
          value: 0.0.0.0
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        # Uncomment if you want to run the CA with TLS enabled.  It is disabled by default. You can also run fabric-ca-server init and customize the fabric-ca-server-config.yaml file.  
        # - name: FABRIC_CA_SERVER_TLS_ENABLED
        #   value: "true"
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: myvolume
        ports:
        - containerPort: 7054
